global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets: ['api-gateway:8443']
    tls_config:
      insecure_skip_verify: true

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: ['product-service:8082']

  - job_name: 'media-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: ['media-service:8083']

  - job_name: 'discovery-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scheme: http
    static_configs:
      - targets: ['discovery-service:8761']
